name: Detailed achievements display
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: NOT_NEEDED
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_achievements_only: sponsor, maintainer, octonaut
